version: "2"

services:
  db:
    image: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_DB=${DB_NAME}
      - POSTGRES_USER=${DB_USERNAME}
      - POSTGRES_PASSWORD=${DB_PASSWORD}
    volumes:
        - db-data:/var/lib/postgresql/data
        # for dadbod using container
        - /tmp:/tmp
volumes:
  db-data:
